### ISSUE TITLE
Bug #12: Selected date not prepopulated in add symptom page

### ISSUE THREAD

**Issue by kenpower** [itcgames/celiapp#14]
### Steps to Reproduce:
select date (other than current date) in calander screen, then click add symptom

### Expected results 
date in add symptom page to be same as slected date in calendar

### Actual Results
date is current date

### Reproducibility Rate:
Every time I carry out these steps

### Severity:
Medium: anything that negatively affects the user experience

#### Reporter: KEN

**Comment by deleojur** [comment]
Perform the same trick for add meal, add emotion and add GIP result
