### ISSUE TITLE
Set daily Goal

### ISSUE THREAD

**Issue by kenpower** [itcgames/celiapp#148]
Set daily goal
Minimum: 1 symptom, 1 meal, 1 energy levels, 0 GIP 
Default: 3 symptoms, 3 meals, 3 energy levels, GIP fixed to 0,3 or 7.
GIP daily goal is 0/1 if Mon Thurs or Sat or 0/0
Calculate daily goal/best day based on 3 day GIP stick

**Comment by deleojur** [comment]
What is meant by _GIP fixed to 0,3 or 7._?

**Comment by deleojur** [comment]
a, I'm gussing there should be a space between 0 and , and 3. Either 0 or 3 or 7.

**Comment by kenpower** [comment]
> What is meant by _GIP fixed to 0,3 or 7._?

user should be allowed to choose 0, 3 or 7 gip sticks per *week* as a goal

**Comment by kenpower** [comment]
> a, I'm gussing there should be a space between 0 and , and 3. Either 0 or 3 or 7.

This is the whole spirit of Erasmus, in a single comment! Bridging cultural divides! :-)

**Comment by deleojur** [comment]
@kenpower could you perhaps look at _Calculate daily goal/best day based on 3 day GIP stick_? My knowledge of this part of the app isn't so great.
The GIP daily goal is now called _gipGoalIndex_ and it can be 
1 = Don't log any gips, 
2 = Log GIPs three times a week (Mon, Thurs and Sat)
3 = Log GIPs daily
