### ISSUE TITLE
Sign up /sign in

### ISSUE THREAD

**Issue by kenpower** [itcgames/celiapp#151]
Sign up or sign in? Isn't sign up when you don't have an account? Havin both options after clicking "I have an account" is weird?

**Comment by itcmartin** [comment]
Yup, I cleaned up the text.

<img width="200" alt="sign-up-improved" src="https://user-images.githubusercontent.com/31845616/121903413-2e0a3300-cd20-11eb-8950-64da4cbcb0e3.png"> <img width="200" alt="sign-in-improved" src="https://user-images.githubusercontent.com/31845616/121903435-35c9d780-cd20-11eb-8366-27632f8333b7.png">
