### ISSUE TITLE
Record symptom

### ISSUE THREAD

**Issue by kenpower** [itcgames/celiapp#16]
Remaining pieces to be done:
-Record no symptom (The first symptom is empty grey circle that says “No symptom” underneath - and no severity bubbles pop up, the grey circle instead is coloured yellow)
-Prompt user about losing symptom data (if the user types a note and presses save or
“You need to select a symptom and severity level by tapping a symptom (from yellow to red) 

https://docs.google.com/document/d/1fH5cDWmOwoiLCL-MLBvNkZyNv5nRR7xp6k-ZocOTGr4/edit#

**Comment by deleojur** [comment]
These requirements have been fixed but got removed by [this](https://github.com/itcgames/celiapp/commit/daf481e90dac7e85c9578adfeaa342565b726c1e) commit.

**Comment by deleojur** [comment]
No symptom shows up without name in the diary.
