### ISSUE TITLE
Move username field above keyboard

### ISSUE THREAD

**Issue by kenpower** [itcgames/celiapp#19]
When logging in on iOS device the virtual keyboard hides the username field

need to move field up when keyboard appears so as not to hide contents

**Comment by kenpower** [comment]
on my android emulator, the input dialog automatically moves up when the onscreen keyboard appears

**Comment by deleojur** [comment]
Where can I find this username field?

**Comment by kenpower** [comment]
To see this problem uninstall the app and reinstall. When entering username/email, the keyboard hides the field

Still a problem on iOS and Androoid
