### ISSUE TITLE
Bug #9: app resets on saving meal

### ISSUE THREAD

**Issue by kenpower** [itcgames/celiapp#3]
## Steps to Reproduce:
Select add meal
Add any details 
Select save
App crashes

## Expected results 
No crash

## Actual Results
Crash, meal not saved

## Reproducibility Rate:
Every time I carry out these steps

## Severity:
High/Critical: anything that impacts the normal user flow or blocks app usage

Date Bug reported: 2/14/2020 9:39:19

**Comment by daireobroin449** [comment]
What build is this on?  And what version of iOS?  I'm testing on build 103 and iPadOS 13.1.1 and it seems to be working fine.

**Comment by kenpower** [comment]
This wa the very first version on TestFlight

Now Can’t reproduce on  iOS 13.3.1 iPhone, build 103
