### ISSUE TITLE
Bug #10: Cannot add meal

### ISSUE THREAD

**Issue by kenpower** [itcgames/celiapp#4]
## Steps to Reproduce:
click +, add meal, give it a name, click save icon

## Expected results 
meal is saved and I get back to the previous screen

## Actual Results
I see the start screen and nothing is saved

## Reproducibility Rate:
Every time I carry out these steps

## Severity:
High/Critical: anything that impacts the normal user flow or blocks app usage

Date Bug reported: 2/14/2020 14:32:43

**Comment by daireobroin449** [comment]
What build is this on?  And what version of iOS?  I'm testing on build 103 and iPadOS 13.1.1 and it seems to be working fine.

**Comment by kenpower** [comment]
Can’t reproduce either iOS 13.3.1 iPhone, build 103
