### ISSUE TITLE
Bug: Streak tracker shows blue circles even when no entries

### ISSUE THREAD

**Issue by kenpower** [itcgames/celiapp#42]
### Steps to Reproduce:
got to streak tracker (middle page)

### Expected results 
grey dot for days with no entries

### Actual Results
all dots are blue even if there are no entries

### Reproducibility Rate:
Every time I carry out these steps

### Severity:
Medium: anything that negatively affects the user experience

### Screenshots:
https://drive.google.com/open?id=1z1M9dgM76x734Aj91Ak4Skd_M4yseAmI

#### Reporter: Ken

**Comment by itcmartin** [comment]
Fixed in 1dab1f1eb924dce44a045a194399cf756ed93ec7.
