### ISSUE TITLE
Bug: Saving GIP image completely breaks the app

### ISSUE THREAD

**Issue by kenpower** [itcgames/celiapp#47]
### Steps to Reproduce:
Open expo on phone, clear storage
Run the app on the device
Fill in a username
Press add GIP
Take an image 
Press save

### Expected results 
Image saves

### Actual Results
An alert with an error occurs (see image)

### Reproducibility Rate:
Every time I carry out these steps

### Severity:
High/Critical: anything that impacts the normal user flow or blocks app usage

### Additional notes:
It only happens with the GIP images - not with meal images.  

The app works fine until you take a GIP image then an alert occurs every time you press something, and the total rows count on the error increments each time.  

Also when you close the app this appears on the npm console
Uploading data for Daire

Row too big to fit into CursorWindow requiredPos=5, totalRows=6
- node_modules\expo-sqlite\build\SQLite.js:36:34 in _deserializeResultSet
- node_modules\expo-sqlite\build\SQLite.js:17:48 in <unknown>
- ... 10 more stack frames from framework internals

### Screenshots:
https://drive.google.com/open?id=1OElCJmoQZspDeTn6h5spY5mDtUJ1bFRs

#### Reporter: Daire

**Comment by kenpower** [comment]
I can’t reproduce in iOS

**Comment by itcmartin** [comment]
I can't reproduce on the BlueStacks Android simulator.

**Comment by kenpower** [comment]
The issue is seems specific too android hardware where there is a limitation in writing more than 2mb at a time to mysql () see links below.

On suggested solution is to compress, but the files are 2.5mb+ after compression.

I think we have to avoid putting images in db, store only the image path in DB (as was done before). and during the database sync with server somehow upload the images directly from device storage.

I think it makes sense that we have the same behaviour with iOS and android.

https://stackoverflow.com/questions/57107489/sqliteblobtoobigexception-row-too-big-to-fit-into-cursorwindow-while-writing-to

https://stackoverflow.com/questions/12716859/retrieve-large-blob-from-android-sqlite-database/12721734#12721734

**Comment by kenpower** [comment]
Thread on this topic https://desqol.slack.com/archives/CUBF0UPPA/p1583756409021000

**Comment by kenpower** [comment]
Fix this bug by reverting the code which adds photos to DB.

have created another story to capture the images https://github.com/itcgames/celiapp/issues/56
