### ISSUE TITLE
Bug #11: cannot pick time

### ISSUE THREAD

**Issue by kenpower** [itcgames/celiapp#5]
## Steps to Reproduce:
Add any entry and click on Choose time

## Expected results 
I see the time picker

## Actual Results
I see a white space. Obviously I can interact with it, something is there - but not visible

## Reproducibility Rate:
Every time I carry out these steps

## Severity:
High/Critical: anything that impacts the normal user flow or blocks app usage

Date Bug reported: 2/14/2020 14:34:55

**Comment by daireobroin449** [comment]
What build is this on?  And what version of iOS?  I'm testing on build 103 and iPad 13.1.1 and it seems to be working fine.
