### ISSUE TITLE
Bug #12: Clicking on the 3 dots in the entry detail crash

### ISSUE THREAD

**Issue by kenpower** [itcgames/celiapp#6]
## Steps to Reproduce:
click on the three dots in the detail view of any entry

## Expected results 
seeing some option

## Actual Results
app restarts

## Reproducibility Rate:
Every time I carry out these steps

## Severity:
Medium: anything that negatively affects the user experience

Date Bug reported: 2/17/2020 9:56:28

**Comment by daireobroin449** [comment]
What build is this on?  And what version of iOS?  I'm testing on build 103 and iPadOS 13.1.1 and the three dots do not appear on the detail view of any entry.
