### ISSUE TITLE
Bug #13: Adding a new meal entry crashes the app

### ISSUE THREAD

**Issue by kenpower** [itcgames/celiapp#7]
## Steps to Reproduce:
Add a meal with any data and try to save it; the app crashes.

## Expected results 
The meal should be saved.

## Actual Results
Crash; app restarts

## Reproducibility Rate:
Every time I carry out these steps

## Severity:
High/Critical: anything that impacts the normal user flow or blocks app usage

Date Bug reported: 2/17/2020 11:02:27

**Comment by daireobroin449** [comment]
What build is this on?  And what version of iOS?  I'm testing on build 103 and iPadOS 13.1.1 and it seems to be working fine.

**Comment by kenpower** [comment]
Can’t reproduce either
