### ISSUE TITLE
Bug: Back Buttons show "TabBar"

### ISSUE THREAD

**Issue by kenpower** [itcgames/celiapp#77]
### Steps to Reproduce:
Go to "Add meal" or show an entry from calendar view like emotion

### Expected results 
Show "back"

### Actual Results
TabBar

### Reproducibility Rate:
Every time I carry out these steps

### Severity:
Minor: ALL else (e.g., typos, missing icons, layout issues, etc.)

### Screenshots:
https://drive.google.com/open?id=1jAGYGjDbT3kpqyL-Ztz1oolYrVemaMnr

#### Reporter: Andreas

**Comment by itcmartin** [comment]
I accidently closed before review.
