### ISSUE TITLE
Database Stability

### ISSUE THREAD

**Issue by daireobroin449** [itcgames/celiapp#82]
Icons change seemingly randomly in some versions.
Fixed when app is fully deleted and reinstalled.

**Comment by itcmartin** [comment]
I investigated the issue and found out the following:

In `DatabaseManager.js` images are imported using:

```
import BLOATING_ICON from '../assets/images/SymptomTracker/bloating.png';
```

and added to the database using:

```
'INSERT OR IGNORE INTO symptoms (id, name, icon, created, modified, usage) VALUES \
(1,  "BLOATING", "' + BLOATING_ICON + '", ' + now + ', ' + now + ', 0)'
```

However, what actually gets added to the database is a number. When React Native imports an image it produces a number, which can then be resolved to fetch the actual image using `Image.resolveAssetSource`. I'm guessing the numbers are not stable between builds.
