### ISSUE TITLE
Main screen

### ISSUE THREAD

**Issue by kenpower** [itcgames/celiapp#92]

**Comment by deleojur** [comment]
This issue is visually done, just waiting for the actual data from the weekly report to connect the input.

**Comment by kenpower** [comment]
@deleojur there is a class called WeeklyReportData , you should be able to get the data you need from it. See the  ReportManager 
https://github.com/itcgames/celiapp/blob/37e606fd8c7d07b09e820e38a044781a831bf952/src/manager/ReportManager.js#L102

for how to use it. There is still discussion about the reporting period, but the WeeklyReportData  can work with any date range provided.

**Comment by deleojur** [comment]
a ok, I thought that it was using only mock data at the moment. I'd prefer to wait so any potential changes can be integrated and the onboarding screens need to be made as well.
